<?php
/**
 * @file
 * DinosaurTest.php
 */

namespace Tests\Unit\AppBundle\Entity;

use AppBundle\Entity\Dinosaur;
use PHPUnit\Framework\TestCase;

/**
 * Class DinosaurTest
 *
 * @package Tests\AppBundle\Entity
 */
class DinosaurTest extends TestCase
{
    /**
     * Tests setting/getting of dinosaur length
     */
    public function testLengthMutators()
    {
        $dinosaur = new Dinosaur();
        $this->assertSame(0, $dinosaur->getLength());

        $dinosaur->setLength(9);
        $this->assertSame(9, $dinosaur->getLength());
    }

    /**
     * Tests dinosaurs do not shrink once post creation
     *
     * Some shrinkage is acceptable
     */
    public function testDinosaurHasNotShrunk()
    {
        $dinosaur = new Dinosaur();
        $dinosaur->setLength(15);

        $this->assertGreaterThan(
            12,
            $dinosaur->getLength(),
            'Did you put in in your washing machine?'
        );
    }

    /**
     * Tests the returned specification of dinosaur.
     *
     * Generated by properties of the dinosaur model, this method ensures
     * default is set as expected
     */
    public function testReturnsFullSpecificationOfDinosaur()
    {
        $dinosaur = new Dinosaur();

        $this->assertSame(
            'The Unknown non-carnivorous dinosaur is 0 meters long',
            $dinosaur->getSpecification()
        );
    }

    /**
     * Tests the returned specification of tyrannosaurus.
     *
     * Creates a dinosaur with altered properties, ensure the generated
     * specification is as expected
     */
    public function testReturnsFullSpecificationForTyrannosaurus()
    {
        $dinosaur = new Dinosaur('Tyrannosaurus', true);
        $dinosaur->setLength(12);

        $this->assertSame(
            'The Tyrannosaurus carnivorous dinosaur is 12 meters long',
            $dinosaur->getSpecification()
        );
    }

}